In [2]:
import yfinance as yf

#define the ticker symbol
tickerSymbol = 'MSFT'

#get data on this ticker
tickerData = yf.Ticker(tickerSymbol)

#get the historical prices for this ticker
tickerDf = tickerData.history(period='1d', start='2010-1-1', end='2020-1-25')

#see your data
tickerDf

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-01-04,23.650096,24.020836,23.626925,23.904980,38409100,0.0,0
2010-01-05,23.827746,24.020840,23.665547,23.912706,49749600,0.0,0
2010-01-06,23.850921,24.005396,23.572867,23.765961,58182400,0.0,0
2010-01-07,23.657819,23.711887,23.317976,23.518793,50559700,0.0,0
2010-01-08,23.387492,23.850916,23.356597,23.680994,51197400,0.0,0
...,...,...,...,...,...,...,...
2020-01-17,164.287913,164.336981,162.335137,163.973907,34371700,0.0,0
2020-01-21,163.561742,165.043502,163.316419,163.385117,29517200,0.0,0
2020-01-22,164.268260,164.356588,162.580437,162.600067,24138800,0.0,0
2020-01-23,163.080914,163.679503,162.178128,163.600998,19680800,0.0,0
2020-01-24,164.376216,164.395846,161.373464,161.952423,24918100,0.0,0

In [3]:
#info on the company
tickerData.info

{'zip': '98052-6399',
 'sector': 'Technology',
 'fullTimeEmployees': 181000,
 'longBusinessSummary': 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); Skype, Outlook.com, OneDrive, and LinkedIn; and Dynamics 365, a set of cloud-based and on-premises business solutions for organizations and enterprise divisions. Its Intelligent Cloud segment licenses SQL, Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also offers support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification on Microsoft products. Its More Personal Computing segment provides Windows original equipment manufacturer (OEM) licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also offers Surface, PC accessories, PCs, tablets, gaming and entertainment consoles, and other devices; Gaming, including Xbox hardware, and Xbox content and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online stores, and retail stores. It has collaborations with Dynatrace, Inc., Morgan Stanley, Micro Focus, WPP plc, ACI Worldwide, Inc., and iCIMS, Inc., as well as strategic relationships with Avaya Holdings Corp. and wejo Limited. Microsoft Corporation was founded in 1975 and is based in Redmond, Washington.',
 'city': 'Redmond',
 'phone': '425 882 8080',
 'state': 'WA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'https://www.microsoft.com',
 'maxAge': 1,
 'address1': 'One Microsoft Way',
 'industry': 'Softwareâ€”Infrastructure',
 'ebitdaMargins': 0.48648998,
 'profitMargins': 0.38515,
 'grossMargins': 0.68864995,
 'operatingCashflow': 81945001984,
 'revenueGrowth': 0.22,
 'operatingMargins': 0.42143002,
 'ebitda': 85745000448,
 'targetLowPrice': 299.93,
 'recommendationKey': 'buy',
 'grossProfits': 115856000000,
 'freeCashflow': 49819750400,
 'targetMedianPrice': 364,
 'currentPrice': 332.8861,
 'earningsGrowth': 0.489,
 'currentRatio': 2.165,
 'returnOnAssets': 0.14589,
 'numberOfAnalystOpinions': 39,
 'targetMeanPrice': 363.88,
 'debtToEquity': 51.938,
 'returnOnEquity': 0.49303,
 'targetHighPrice': 410,
 'totalCash': 130584002560,
 'totalDebt': 78934999040,
 'totalRevenue': 176250994688,
 'totalCashPerShare': 17.393,
 'financialCurrency': 'USD',
 'revenuePerShare': 23.395,
 'quickRatio': 1.961,
 'recommendationMean': 1.7,
 'exchange': 'NMS',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-18000000',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'messageBoardId': 'finmb_21835',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 13.974,
 'beta3Year': None,
 'enterpriseToEbitda': 28.724,
 '52WeekChange': 0.5813031,
 'morningStarRiskRating': None,
 'forwardEps': 10.53,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 7507979776,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'totalAssets': None,
 'bookValue': 20.242,
 'sharesShort': 41195079,
 'sharesPercentSharesOut': 0.0055,
 'fundFamily': None,
 'lastFiscalYearEnd': 1625011200,
 'heldPercentInstitutions': 0.71874,
 'netIncomeToCommon': 67882999808,
 'trailingEps': 8.939,
 'lastDividendValue': 0.62,
 'SandP52WeekChange': 0.27606308,
 'priceToBook': 16.445316,
 'heldPercentInsiders': 0.00067000004,
 'nextFiscalYearEnd': 1688083200,
 'yield': None,
 'mostRecentQuarter': 1632960000,
 'shortRatio': 1.73,
 'sharesShortPreviousMonthDate': 1634256000,
 'floatShares': 7500998022,
 'beta': 0.872727,
 'enterpriseValue': 2462923882496,
 'priceHint': 2,
 'threeYearAverageReturn': None,
 'lastSplitDate': 1045526400,
 'lastSplitFactor': '2:1',
 'legalType': None,
 'lastDividendDate': 1637107200,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 0.476,
 'priceToSalesTrailing12Months': 14.180358,
 'dateShortInterest': 1636934400,
 'pegRatio': 2.2,
 'ytdReturn': None,
 'forwardPE': 31.613117,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0055,
 'sharesShortPriorMonth': 48556022,
 'impliedSharesOutstanding': None,
 'category': None,
 'fiveYearAverageReturn': None,
 'previousClose': 334.92,
 'regularMarketOpen': 335.31,
 'twoHundredDayAverage': 278.88055,
 'trailingAnnualDividendYield': 0.006867311,
 'payoutRatio': 0.25059998,
 'volume24Hr': None,
 'regularMarketDayHigh': 335.49,
 'navPrice': None,
 'averageDailyVolume10Day': 31454330,
 'regularMarketPreviousClose': 334.92,
 'fiftyDayAverage': 318.4162,
 'trailingAnnualDividendRate': 2.3,
 'open': 335.31,
 'toCurrency': None,
 'averageVolume10days': 31454330,
 'expireDate': None,
 'algorithm': None,
 'dividendRate': 2.48,
 'exDividendDate': 1637107200,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 330.8,
 'currency': 'USD',
 'trailingPE': 37.239746,
 'regularMarketVolume': 16019111,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 2499302129664,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 25615552,
 'dayLow': 330.8,
 'ask': 332.81,
 'askSize': 800,
 'volume': 16019111,
 'fiftyTwoWeekHigh': 349.67,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 1.42,
 'fiftyTwoWeekLow': 209.11,
 'bid': 332.79,
 'tradeable': False,
 'dividendYield': 0.0076,
 'bidSize': 1400,
 'dayHigh': 335.49,
 'regularMarketPrice': 332.8861,
 'preMarketPrice': 335.42,
 'logo_url': 'https://logo.clearbit.com/microsoft.com'}

In [4]:
#get event data for ticker
tickerData.calendar

                                    0                    1
Earnings Date     2022-01-24 10:59:00  2022-01-28 12:00:00
Earnings Average                 2.31                 2.31
Earnings Low                     2.27                 2.27
Earnings High                    2.46                 2.46
Revenue Average           50830400000          50830400000
Revenue Low               50536700000          50536700000
Revenue High              51555000000          51555000000

In [6]:
#get recommendation data for ticker
tickerData.recommendations

                               Firm       To Grade From Grade Action
Date
2012-03-16 08:19:00  Argus Research            Buy                up
2012-03-19 14:00:00  Hilliard Lyons  Long-Term Buy              main
2012-03-22 07:03:00  Morgan Stanley     Overweight              main
2012-04-03 11:53:00             UBS            Buy              main
2012-04-20 06:18:00   Deutsche Bank            Buy              main
...                             ...            ...        ...    ...
2021-10-27 12:37:42   Credit Suisse     Outperform              main
2021-10-27 13:41:53        Barclays     Overweight              main
2021-10-27 13:56:33  Morgan Stanley     Overweight              main
2021-10-28 14:55:44       Citigroup            Buy              main
2021-11-02 09:45:19   Deutsche Bank            Buy              init

[358 rows x 4 columns]